title: SlyTech Blog
description: Homelab, cybersecurity, and infrastructure writeups by Sly
url: "https://blog.slytech.us"
theme: minima

author:
  name: Sly

show_excerpts: true

minima:
  skin: dark
